### ISSUE TITLE
Notebook-friendly progress bars

### ISSUE THREAD

**Issue by SynapticSage** [nteract/papermill#165]
Would it be useful to let users switch tqdm() to the module's tqdm_notebook() function? It works exactly the same, but prints progress bars better in notebooks, without forcing new progress messages onto a new line. Perhaps an interface could be exposed for users to set that function instance?

**Comment by betatim** [comment]
Two ideas:

1. do people who run `papermill -p blah foo input.ipynb out/notebook.ipynb` on the command-line actually like seeing a progressbar? For me it is Ok that it is there but I don't particularly care for it. If no one loves it maybe we only have a progress-bar when called from Python?

1. allow users to choose the kind of progress-bar when they call papermill. The default if you are using papermill as a Python library could be "notebook style" and when it is called via the command line "terminal style" is the default.

I'd avoid trying to guess, that tends to go wrong too often, at which point you need the option for the user to specify it anyway :-/

**Comment by MSeal** [comment]
1) has definitely been useful for users I've worked with. It gives initial trust that the tool is working and that it's not just stuck before it starts actual work.

2) Engines PR just merged which tries to be smart about it (so far in testing it works as expected in all environments). I think we could easily extend it to allow for user assignment if that makes sense for someone.

**Comment by MSeal** [comment]
Since this issue got resolved with the merge of the engine PR, are we ok with closing this issue? We could open a new one if there's discussion of how to parameterize or change progress bar behavior elsewhere.

**Comment by betatim** [comment]
I'm good with closing.

**Comment by huynhducloi00** [comment]
the progress bar is printed on every line using papermill. this issue is NOT fixed.
